Repository openshift/machine-api-provider-nutanix, pull requests merged in 2025-07, with the labels that each got.

#111 OCPBUGS-51859: CVE-2025-22868
  go.mod
  go.sum
  vendor/golang.org/x/oauth2/LICENSE
  vendor/golang.org/x/oauth2/README.md
  vendor/golang.org/x/oauth2/internal/client_appengine.go
  vendor/golang.org/x/oauth2/internal/transport.go
  vendor/golang.org/x/oauth2/oauth2.go
  vendor/golang.org/x/oauth2/token.go
  vendor/google.golang.org/appengine/LICENSE
  vendor/google.golang.org/appengine/internal/api.go
  vendor/google.golang.org/appengine/internal/api_classic.go
  vendor/google.golang.org/appengine/internal/api_common.go
  vendor/google.golang.org/appengine/internal/app_id.go
  vendor/google.golang.org/appengine/internal/base/api_base.pb.go
  vendor/google.golang.org/appengine/internal/base/api_base.proto
  vendor/google.golang.org/appengine/internal/datastore/datastore_v3.pb.go
  vendor/google.golang.org/appengine/internal/datastore/datastore_v3.proto
  vendor/google.golang.org/appengine/internal/identity.go
  vendor/google.golang.org/appengine/internal/identity_classic.go
  vendor/google.golang.org/appengine/internal/identity_flex.go
  vendor/google.golang.org/appengine/internal/identity_vm.go
  vendor/google.golang.org/appengine/internal/internal.go
  vendor/google.golang.org/appengine/internal/log/log_service.pb.go
  vendor/google.golang.org/appengine/internal/log/log_service.proto
  vendor/google.golang.org/appengine/internal/main.go
  vendor/google.golang.org/appengine/internal/main_common.go
  vendor/google.golang.org/appengine/internal/main_vm.go
  vendor/google.golang.org/appengine/internal/metadata.go
  vendor/google.golang.org/appengine/internal/net.go
  vendor/google.golang.org/appengine/internal/regen.sh
  vendor/google.golang.org/appengine/internal/remote_api/remote_api.pb.go
  vendor/google.golang.org/appengine/internal/remote_api/remote_api.proto
  vendor/google.golang.org/appengine/internal/transaction.go
  vendor/google.golang.org/appengine/internal/urlfetch/urlfetch_service.pb.go
  vendor/google.golang.org/appengine/internal/urlfetch/urlfetch_service.proto
  vendor/google.golang.org/appengine/urlfetch/urlfetch.go
  vendor/modules.txt
Labels: ok-to-test, cherry-pick-approved, approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#110 OCPBUGS-51854: CVE-2025-22868
  go.mod
  go.sum
  vendor/golang.org/x/oauth2/LICENSE
  vendor/golang.org/x/oauth2/README.md
  vendor/golang.org/x/oauth2/deviceauth.go
  vendor/golang.org/x/oauth2/internal/client_appengine.go
  vendor/golang.org/x/oauth2/internal/transport.go
  vendor/golang.org/x/oauth2/oauth2.go
  vendor/golang.org/x/oauth2/pkce.go
  vendor/golang.org/x/oauth2/token.go
  vendor/google.golang.org/appengine/LICENSE
  vendor/google.golang.org/appengine/internal/api.go
  vendor/google.golang.org/appengine/internal/api_classic.go
  vendor/google.golang.org/appengine/internal/api_common.go
  vendor/google.golang.org/appengine/internal/app_id.go
  vendor/google.golang.org/appengine/internal/base/api_base.pb.go
  vendor/google.golang.org/appengine/internal/base/api_base.proto
  vendor/google.golang.org/appengine/internal/datastore/datastore_v3.pb.go
  vendor/google.golang.org/appengine/internal/datastore/datastore_v3.proto
  vendor/google.golang.org/appengine/internal/identity.go
  vendor/google.golang.org/appengine/internal/identity_classic.go
  vendor/google.golang.org/appengine/internal/identity_flex.go
  vendor/google.golang.org/appengine/internal/identity_vm.go
  vendor/google.golang.org/appengine/internal/internal.go
  vendor/google.golang.org/appengine/internal/log/log_service.pb.go
  vendor/google.golang.org/appengine/internal/log/log_service.proto
  vendor/google.golang.org/appengine/internal/main.go
  vendor/google.golang.org/appengine/internal/main_common.go
  vendor/google.golang.org/appengine/internal/main_vm.go
  vendor/google.golang.org/appengine/internal/metadata.go
  vendor/google.golang.org/appengine/internal/net.go
  vendor/google.golang.org/appengine/internal/regen.sh
  vendor/google.golang.org/appengine/internal/remote_api/remote_api.pb.go
  vendor/google.golang.org/appengine/internal/remote_api/remote_api.proto
  vendor/google.golang.org/appengine/internal/transaction.go
  vendor/google.golang.org/appengine/internal/urlfetch/urlfetch_service.pb.go
  vendor/google.golang.org/appengine/internal/urlfetch/urlfetch_service.proto
  vendor/google.golang.org/appengine/urlfetch/urlfetch.go
  vendor/modules.txt
Labels: ok-to-test, cherry-pick-approved, approved, lgtm, qe-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#109 OCPBUGS-51850: CVE-2025-22868
  go.mod
  go.sum
  vendor/golang.org/x/oauth2/LICENSE
  vendor/golang.org/x/oauth2/README.md
  vendor/golang.org/x/oauth2/deviceauth.go
  vendor/golang.org/x/oauth2/internal/client_appengine.go
  vendor/golang.org/x/oauth2/internal/token.go
  vendor/golang.org/x/oauth2/internal/transport.go
  vendor/golang.org/x/oauth2/oauth2.go
  vendor/golang.org/x/oauth2/pkce.go
  vendor/golang.org/x/oauth2/token.go
  vendor/google.golang.org/appengine/LICENSE
  vendor/google.golang.org/appengine/internal/api.go
  vendor/google.golang.org/appengine/internal/api_classic.go
  vendor/google.golang.org/appengine/internal/api_common.go
  vendor/google.golang.org/appengine/internal/app_id.go
  vendor/google.golang.org/appengine/internal/base/api_base.pb.go
  vendor/google.golang.org/appengine/internal/base/api_base.proto
  vendor/google.golang.org/appengine/internal/datastore/datastore_v3.pb.go
  vendor/google.golang.org/appengine/internal/datastore/datastore_v3.proto
  vendor/google.golang.org/appengine/internal/identity.go
  vendor/google.golang.org/appengine/internal/identity_classic.go
  vendor/google.golang.org/appengine/internal/identity_flex.go
  vendor/google.golang.org/appengine/internal/identity_vm.go
  vendor/google.golang.org/appengine/internal/internal.go
  vendor/google.golang.org/appengine/internal/log/log_service.pb.go
  vendor/google.golang.org/appengine/internal/log/log_service.proto
  vendor/google.golang.org/appengine/internal/main.go
  vendor/google.golang.org/appengine/internal/main_common.go
  vendor/google.golang.org/appengine/internal/main_vm.go
  vendor/google.golang.org/appengine/internal/metadata.go
  vendor/google.golang.org/appengine/internal/net.go
  vendor/google.golang.org/appengine/internal/regen.sh
  vendor/google.golang.org/appengine/internal/remote_api/remote_api.pb.go
  vendor/google.golang.org/appengine/internal/remote_api/remote_api.proto
  vendor/google.golang.org/appengine/internal/transaction.go
  vendor/google.golang.org/appengine/internal/urlfetch/urlfetch_service.pb.go
  vendor/google.golang.org/appengine/internal/urlfetch/urlfetch_service.proto
  vendor/google.golang.org/appengine/urlfetch/urlfetch.go
  vendor/modules.txt
Labels: ok-to-test, cherry-pick-approved, approved, lgtm, qe-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#118 NO-JIRA: Update OWNERS
  OWNERS
Labels: approved, lgtm, jira/valid-reference
